// commands/fun/words.j// commands/wortds.js

const sozlerBazasi = [
  "Uğur qazanmaq istəyirsənsə, heç vaxt dayanma! 💪",
  "Həyat sən planlar qurarkən başına gələnlərdir. 🌀",
  "Bu gün yeni bir başlanğıc üçün ən gözəl gündür. ✨",
  "Əgər çətinlik çəkirsənsə, deməli inkişaf edirsən. 📈",
  "Hər qaranlıq gecənin bir sabahı var, ümidini itirmə. 🌅",
  "Dahi olmaq üçün deyil, dahi qalmaq üçün çalışmaq lazımdır. 🧠",
  "Böyük işlər görmək üçün ilk növbədə kiçik addımlara inanmalısan. 👣",
  "Bu gün etdiyin seçimlər, sabahkı gələcəyini yaradır. 🎯",
  "Yıxılmaq uğursuzluq deyil, yıxılıb qorxub ayağa qalxmamaq uğursuzluqdur. 🧗",
  "Başlamaq üçün mükəmməl olmaq məcburiyyətində deyilsən, amma mükəmməl olmaq üçün başlamaq məcburiyyətindəsən. 🚀",
  "Dünən xəyal olan şeylər, bu günün reallığı, sabahın isə keçmişidir. ⏳",
  "Heç vaxt keçmişdə yaşama, amma keçmişdən aldığın dərsləri gələcəyin üçün qalxan et. 🛡️",
  "Ən böyük risk, heç bir riskə girməməkdir. 🎲",
  "Səssizcə çalış, burax uğurun sənin səs-küyün olsun. 🤫🏆",
  "Xəyallarının arxasınca qaç, çünki qaçmasan, onlar sadəcə bir xəyal olaraq qalacaq. 🌠",
  "İnkişaf etmək istəyirsənsə, rahatlıq zonandan çıxmağı öyrənməlisən. ⛺",
  "Həyat bir velosiped sürmək kimidir; balansı qorumaq üçün hərəkət etməyə davam etməlisən. 🚴",
  "Başqalarının sənin haqqında nə düşündüyü, sənin reallığın olmaq məcburiyyətində deyil. 💎",
  "Əgər bir şeyi xəyal edə bilirsənsə, deməli onu edə bilərsən. 🌌",
  "Uğurun sirri, məqsədə olan sadiqlikdə və hər gün atılan kiçik addımlardadır. 🗝️",
  "Bütün böyük çaylar kiçik bulaqlardan başlayır. 💧🌊",
  "Bu gün hər kəsin etmədiyi şeyi etsən, sabah hər kəsin sahib ola bilmədiyi şeyə sahib olarsan.👑",
  "Ən böyük qalibiyyət, özünə qarşı qazandığın qalibiyyətdir. 🏅",
  "Zaman ən dəyərli sərvətdir; onu səni irəli aparmayan insanlara xərcləmə. ⏱️",
  "Problemlərə maneə kimi yox, güclənmək üçün bir fürsət kimi bax. ⚡",
  "Çətin yollar həmişə gözəl mənzərələrə çıxır. 🏔️☀️",
  "Səbr sadəcə gözləmək deyil, gözləyərkən doğru mövqedə qala bilməkdir. 🕯️",
  "Dünəni dəyişdirə bilməzsən, amma bu günü elə yaşaya bilərsən ki, sabahın parlaq olsun. ☀️",
  "Başqalarını keçmək üçün yox, dünənki özünü keçmək üçün çalış. 🏃‍♂️",
  "Həyat sənə min bir çətinlik göstərəndə, sən də ona min bir gücün olduğunu göstər. 🔥",
  "Kiçik şeylərdən zövq almağı öyrən, çünki bir gün geriyə baxanda onların böyük şeylər olduğunu anlayacaqsan. 🌸",
  "Hər bir uğursuzluq, uğura gedən yolda sadəcə bir təcrübədir. 🎓",
  "Özünə inan; sən düşündüyündən daha güclü, daha ağıllı və daha istedadlısan. ⭐",
  "Heç vaxt kölgədə qalanlardan olma, öz işığını özün yarat. 💡",
  "Həyatda ən baha şey zamandır; itirilən pullar geri gəlir, amma itirilən saniyələr əsla. ⌛",
  "İstedad sənə qapını açar, amma xarakter səni o otaqda saxlayar. 🚪",
  "Fikir verdiyin şeylər böyüyər; problemlərə yox, həll yollarına fokuslan. 🔍",
  "Uğur təsadüf deyil; o, zəhmət, fədakarlıq və öyrənməyin nəticəsidir. 📚",
  "Əgər hər kəsin getdiyi yolla getsən, hamının çatdığı yerə çatacaqsan. Öz yolunu cız! 🗺️",
  "Nə qədər yavaş getdiyinin önəmi yoxdur, yetər ki, dayanmayasan. 🐢",
  "Uğursuz olmaqdan qorxma, cəhd etməməkdən qorx. 🦅",
  "Həyatın dadını çıxarmaq üçün mükəmməl anı gözləmə, mövcud anı mükəmməl et. 🍀",
  "Düşüncələrini dəyişdir, dünyan dəyişsin. 🗺️🧠",
  "Yaxşı şeylər vaxt aparır; tələsmə, amma gecikmə də. 🪐",
  "Qaranlıqdan şikayət edincə bir şam da sən yandır. 🕯️",
  "Dürüstlük ən yaxşı siyasətdir və ən güclü xarakter göstəricisidir. 🤝",
  "Bilgi gücdür, amma onu tətbiq etmək əsl müdriklikdir. 📖✨",
  "Sən özünü qiymətləndirməsən, heç kəs səni qiymətləndirməyəcək. 💎",
  "Böyük xəyallar quranlar böyük işlər görərlər. 🌌🛸",
  "Hər gün özün üçün yaxşı bir şey et; məsələn, yeni bir şey öyrən. 🧠🔋",
  "Həyat sənə limon verirsə, ondan limonad düzəlt. 🍋🍹",
  "Əgər uçmaq istəyirsənsə, səni aşağı çəkən hər şeyi geridə qoymalısan. 🎈🦅",
  "Uğur, hər yıxılanda bir az daha güclü şəkildə ayağa qalxmaqdır. 💥🤸",
  "Gözəl günlər sənə gəlməyəcək, sən onlara doğru yürüməlisən. 🚶‍♂️🌈",
  "Əgər daxilində sülh varsa, xaricdəki heç bir fırtına səni sarsıda bilməz. 🧘‍♂️🌊",
  "Əsl dost sənə həqiqətləri söyləyən və çətin anında yanında olandır. 🤝",
  "Şükür etmək sahib olduqlarını artırar, şikayət etmək isə daxili enerjini tükədər. 🔋",
  "Uğurlu insanla uğursuz insan arasındakı fərq bilik yox, iradə fərqidir. 🔥",
  "Başqasının bağçasındakı güllərə baxmaqdansa, öz bağçanı sula. 🏡🌹",
  "Həyat sınaqlardan ibarətdir; hər sınaq isə səni yeni bir mərhələyə hazırlayır. 📝",
  "Bəhanələr səni heç vaxt hədəfinə çatdırmayacaq; hərəkətə keç! 🎬🏃‍♂️",
  "Hər gün yeni bir səhifədir; bu gün öz hekayəni gözəl yaz. 📖✍️",
  "Ən güclü silah, səbr və zamandır. 🏹⌛",
  "Heç vaxt özünü başqaları ilə müqayisə etmə; sən unikal və təkrarolunmazsan. ✨🏺",
  "Bilik paylaşıldıqca çoxalan yeganə xəzinədir. 💎🧠",
  "Həyat sənə inanmayanları haqsız çıxarmaq üçün ən gözəl arenadır. 🏟️🔥",
  "Əgər içində heç bir şübhə yoxdursa, kənardakı heç bir söz səni yolundan döndərə bilməz. 🎯",
  "Uğura gedən lift xarabdır; sən pilləkənlərlə bir-bir qalxmalısan. 🪜🏃‍♂️",
  "Uğur qazanmaq üçün öncə özünə olan hörmətini qorumalısan. 👑",
  "Zirvəyə qalxmaq çətindir, amma oradakı mənzərə bütün yorğunluğa dəyər. 🏔️🦅",
  "Heç bir külək hədəfi olmayan gəmiyə kömək edə bilməz. ⛵💨",
  "Ağlını təmiz tut, çünki düşüncələrin tezliklə sözlərinə və əməllərinə çevriləcək. 🧠🌱",
  "Həyat sənə qarşı sərt davrananda, sən özünə qarşı mehriban olmağı unutma. 🤍",
  "Həqiqi zənginlik cibindəki pullarla yox, ruhundakı rahatlıqla ölçülür. 🪙🧘‍♂️",
  "Böyük nəticələr böyük fədakarlıqlar tələb edir. 🔥🎯",
  "Hər sabah yuxudan duranda özünə söz ver: Dünənkindən daha yaxşı olacam. ☀️",
  "Həyat qısadır; lazımsız mübahisələrə və kin bəsləməyə vaxt xərcləmə. 👋",
  "Sən öz gələcəyinin memarısan; binanı möhkəm təməllər üzərində qur. 🏗️🏠",
  "Ətrafındakı insanların səviyyəsi sənin gələcəyini müəyyən edir; seçimlərində diqqətli ol.👥",
  "Ən böyük səhv, səhv etməkdən qorxub heç nə etməməkdir. 🚫🎲",
  "Hər qışın arxasında bir bahar, hər çətinliyin arxasında bir asanlıq gizlənib. ❄️🌸",
  "Gözəl söz daxili mədəniyyətin, gözəl əməl isə əsl insanlığın aynasıdır. 🪞✨",
  "Yalnız risk edənlər nə qədər irəli gedə biləcəklərini öyrənirlər. 🌊🧭",
  "Öyrənməyi dayandıran insan qocalmış deməkdir, istər 20 yaşında olsun, istər 80. 📚🧠",
  "Həyatda hər şey keçicidir; sevinclər də, kədərlər də. Balansı qoru. ⚖️",
  "Öz hekayənin qəhrəmanı sən ol, başqalarının ssenarisində epizodik rol oynama. 🎬👑",
  "Yaxşı başlanğıc işin yarısı deməkdir, amma sonunadək getmək qalibiyyətdir. 🏁",
  "Həyat sənin baxış bucağından asılıdır; haraya baxırsansa, oranın rəngini görürsən. 🎨📊",
  "Özünə investisiya etmək, edə biləcəyin ən gəlirli və ən etibarlı sərmayədir. 📈🧠",
  "Məqsədin yoxdursa, sadəcə zamanın axını ilə sovrulub gedən bir yarpaq olacaqsan. 🍁🍂",
  "Zəfər, 'mən bacaracam' deyib yola çıxan və geri dönməyənlərindir. ⚔️🛡️",
  "Xoşbəxtlik bir hədəf deyil, səyahət formasıdır. 🗺️🚗",
  "Sözlərinə diqqət et; onlar həm yaralaya, həm də şəfa verə bilər. 🗣️🩹",
  "İnkişaf ağrılıdır, dəyişiklik ağrılıdır, amma heç biri aid olmadığın yerdə qalmaq qədər ağrılı deyil.🐾",
  "Həyatın sirlərini açmaq istəyirsənsə, əvvəlcə öz daxili dünyanı kəşf et. 🕯️🌌",
  "Zəhmət çəkmədən qazanılan uğur, sabun köpüyü kimi tez yox olar. 🧼🫧",
  "Təvazökarlıq insanı ucaldar, təkəbbür isə ən yüksəkdən yerə çırpar. ⚖️👑",
  "Hər işdə bir xeyir var; bəzən dualarının qəbul olunmaması da sənin üçün ən böyük xeyirdir.🕯️",
  "Bu gün əlindən gələnin ən yaxşısını et və nəticəni zamana burax. 🎯⏱️",
  "Gələcəyi təxmin etməyin ən yaxşı yolu, onu öz əllərinlə yaratmaqdır. 🛠️✨"
];

module.exports = sozlerBazasi;


